# Generated by Django 5.2.4 on 2025-08-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiovideomedia",
            name="checksum",
        ),
        migrations.RemoveField(
            model_name="imagemedia",
            name="checksum",
        ),
        migrations.AlterField(
            model_name="audiovideomedia",
            name="encoded_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="audiovideomedia",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("PROCESSING", "PROCESSING"),
                    ("COMPLETED", "COMPLETED"),
                    ("ERROR", "ERROR"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
        migrations.AlterModelTable(
            name="video",
            table="video",
        ),
    ]
